### ISSUE TITLE
Add support for python 3.12

### ISSUE THREAD

**Issue by FritjofH** [conda-forge/python-minifier-feedstock#7]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In https://github.com/conda-forge/python-minifier-feedstock/pull/6 minfier 2.10 was added. As you can see in https://github.com/dflook/python-minifier/releases/tag/2.10.0 the main feature of the 2.10 release is support for python 3.12 which is not supported here.

From what I can tell all that is needed is to change the `< 3.12` to a `<= 3.12` in the meta.yml.

### Installed packages

```shell
.
```

### Environment info

```shell
Could not solve for environment specs
The following packages are incompatible
├─ python 3.12**  is installable with the potential options
│  ├─ python [3.12.0|3.12.1|3.12.2|3.12.3] would require
│  │  └─ tk >=8.6.13,<8.7.0a0 , which can be installed;
│  ├─ python 3.12.0rc3 would require
│  │  └─ _python_rc, which does not exist (perhaps a missing channel);
│  └─ python [3.12.4|3.12.5|3.12.6] would require
│     └─ libzlib >=1.3.1,<2.0a0  with the potential options
│        ├─ libzlib 1.3.1 would require
│        │  └─ zlib 1.3.1 *_0, which can be installed;
│        └─ libzlib 1.3.1 would require
│           └─ zlib 1.3.1 *_1, which can be installed;
├─ tk 8.6.12.*  is not installable because it conflicts with any installable versions previously reported;
└─ zlib 1.2.13.*  is not installable because it conflicts with any installable versions previously reported.
```

**Comment by thewchan** [comment]
@FritjofH confirmed upstream that the supported python versions are `python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, <3.13'`. I can update the recipe with this change.

**Comment by FritjofH** [comment]
Great! I'll close my PR as we did the same work then. Thanks for the quick fix!

**Comment by thewchan** [comment]
Fixed via https://github.com/conda-forge/python-minifier-feedstock/pull/8
